### ISSUE TITLE
Does work?

### ISSUE THREAD

**Issue by DolceJ0Lly** [Hazza3100/MassServerLeave#2]
I tried and when i put the token wait like 0,0025 seconds and says C:\Users\.\desktop> why doesnt work at me?

**Comment by Hazza3100** [comment]
Try print the exception 

where it says Except Exception change it to Except Exception as e:
print(e)

**Comment by DolceJ0Lly** [comment]
Can't find it, where is? if u can tell me the N° of the line. ty

**Comment by Hazza3100** [comment]
> Can't find it, where is? if u can tell me the N° of the line. ty

Line number 28 where it says “except:”.

**Comment by DolceJ0Lly** [comment]
found an error:
```
Traceback (most recent call last):
  File "C:\Users\fiokoly\OneDrive\Desktop\hosting\!MassLeaveServerDiscord\py.py", line 18, in leave
    if guild['id'] in self.dontLeave:
       ~~~~~^^^^^^
TypeError: string indices must be integers, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fiokoly\OneDrive\Desktop\hosting\!MassLeaveServerDiscord\py.py", line 32, in <module>
    Cleaner(input("Account token: ")).leave()
  File "C:\Users\fiokoly\OneDrive\Desktop\hosting\!MassLeaveServerDiscord\py.py", line 29, in leave
    print(e)
          ^
NameError: name 'e' is not defined
```
**_(yea i put the token) ç_ç_**

**Comment by Hazza3100** [comment]
You didn’t define e when using except Exception as

**Comment by DolceJ0Lly** [comment]
Sorry, can u leave me a full code on pastebin or smth like that? Beacuse i have an laptop and i use notepad (bad) for modify codes

**Comment by Hazza3100** [comment]
A laptop is sufficient to write some code - install visual studio code instead of notepad.

**Comment by DolceJ0Lly** [comment]
what's number line

**Comment by DolceJ0Lly** [comment]
hi, just an update, it works, and i used it, but i needed to do python (filename).py multiple times to leave all the servers
